{{- range .Values.chains }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-{{ .id }}
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: router-{{ .id }}
  template:
    metadata:
      labels:
        app: router-{{ .id }}
    spec:
      containers:
        - name: router
          image: router
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ dig "router" "resources" "requests" "cpu" "100m" . }}
              memory: {{ dig "router" "resources" "requests" "memory" "256Mi" . }}
            limits:
              cpu: {{ dig "router" "resources" "limits" "cpu" "1000m" . }}
              memory: {{ dig "router" "resources" "limits" "memory" "2Gi" . }}
            # requests:
            #   cpu: 1250m
            #   memory: 2Gi
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 120 # 120 * 10s = 20 minutes to start
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3 
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: CHAIN_ID
              value: "{{ .id }}"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: DRPC_ID
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_ENVIRONMENT
{{- end }}