apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-default
  template:
    metadata:
      labels:
        app: extractor-default
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          # resources:
          #   requests:
          #     memory: "8Gi"
          #     cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
            terminationGracePeriodSeconds: 60
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: CONFIG_GROUP
              value: "DEFAULT"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-1
  template:
    metadata:
      labels:
        app: extractor-1
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          # resources:
          #   requests:
          #     memory: "8Gi"
          #     cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
            terminationGracePeriodSeconds: 60
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: CONFIG_GROUP
              value: "1"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-56
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-56
  template:
    metadata:
      labels:
        app: extractor-56
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          # resources:
          #   requests:
          #     memory: "8Gi"
          #     cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
            terminationGracePeriodSeconds: 60
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: CONFIG_GROUP
              value: "56"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-137
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-137
  template:
    metadata:
      labels:
        app: extractor-137
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          # resources:
          #   requests:
          #     memory: "8Gi"
          #     cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
            terminationGracePeriodSeconds: 60
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: CONFIG_GROUP
              value: "137"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
