{{- $pruning := .Values.pruning -}}
{{- range .Values.chains }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-{{ .id }}
spec:
  selector:
    matchLabels:
      app: extractor-{{ .id }}
  template:
    metadata:
      labels:
        app: extractor-{{ .id }}
    spec:
      volumes:
        - name: extractor-pv
          persistentVolumeClaim:
            claimName: extractor-pvc
      serviceAccountName: extractor
      {{ if eq $pruning true }}
      initContainers:
        - name: extractor-init
          image: extractor-init
          volumeMounts:
            - mountPath: "/app/cache"
              subPath: "{{ .id }}"
              name: extractor-pv
          env:
            - name: CHAIN_ID
              value: "{{ .id }}"
            - name: CACHE_DIR
              value: "/app/cache"
      {{ end }}
      containers:
        - name: extractor
          image: extractor
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/app/cache"
              subPath: "{{ .id }}"
              name: extractor-pv
          resources:
            requests:
              cpu: {{ dig "extractor" "resources" "requests" "cpu" "50m" . }}
              memory: {{ dig "extractor" "resources" "requests" "memory" "325Mi" . }}
            limits:
              cpu: {{ dig "extractor" "resources" "limits" "cpu" "1000m" . }}
              memory: {{ dig "extractor" "resources" "limits" "memory" "8Gi" . }}
          startupProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 150 # 150 * 10s = 25 minutes to start
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          env:
            - name: CHAIN_ID
              value: "{{ .id }}"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: DRPC_ID
            - name: RSK_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: RSK_ID
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_ENVIRONMENT
{{- end }}