apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sushi-api-staging-ingress
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "sushi-api-staging-ip"
    networking.gke.io/managed-certificates: "sushi-api-staging-managed-certificate"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      gzip on;
      gzip_types application/json;
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: sushi-api-staging-managed-certificate
spec:
  domains:
    - staging.sushi.com