

{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: extractor-{{ $value }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: extractor-{{ $value }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: '100m'
          memory: '100Mi'
        maxAllowed:
          cpu: '1000m'
          memory: '500Mi'
        controlledResources: ["cpu", "memory"]
{{- end }}