{{- range .Values.chains }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: extractor-{{ .id }}=
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-{{ .id }}
  template:
    metadata:
      labels:
        app: extractor-{{ .id }}
    spec:
      containers:
        - name: extractor
          image: extractor
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /app/cache
              name: extractor-{{ .id }}-cache
          env:
            - name: CHAIN_ID
              value: "{{ .id }}"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: DRPC_ID
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_ENVIRONMENT
  volumeClaimTemplates:
  - metadata:
      name: extractor-{{ .id }}-cache
    spec:
      accessModes: ["ReadWriteOncePod"]
      resources:
        requests:
          storage: 250Mi
{{- end }}