{{- range .Values.chains }}
apiVersion: v1
kind: Service
metadata:
  name: extractor-{{ .id }}-service
  namespace: extractor
spec:
  selector:
    app: extractor-{{ .id }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
{{- end }}