

{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: extractor-{{ $value }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: extractor-{{ $value }}
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: extractor
        minAllowed:
          cpu: 250m
          memory: 500Mi
        maxAllowed:
          cpu: 1000m
          memory: 1000Mi
        controlledResources: ["cpu", "memory"]
{{- end }}