apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 8;
    # worker_cpu_affinity auto;
    worker_rlimit_nofile 10240;
    events {
      worker_connections 10240;
    }
    http { 
      {{- $chainIds := .Values.chainIds }}
      {{- range $index, $value := $chainIds }}
      upstream router-{{ $value }} {
        zone upstreams 64K;
        # server router-{{ $value }} max_fails=1 fail_timeout=2s;
        server router-{{ $value }};
        keepalive 2;
      }
      {{- end }}
      
      map $uri $proxy_pass {
        ~^/(\w+)/(\w+)/(\d+) router-$3;
      }

      server { 
        listen 80;
        location / {
          proxy_http_version 1.1;
          proxy_set_header "Connection" "";
          proxy_pass http://$proxy_pass;
        }
        location /health {
          auth_basic off;
          return 200;
        }
      } 
    }