{{- range .Values.chains }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-{{ .id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-{{ .id }}
  template:
    metadata:
      labels:
        app: router-{{ .id }}
    spec:
      # nodeSelector:
      #   cloud.google.com/compute-class: Scale-Out
      containers:
        - name: router
          image: router
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              ephemeral-storage: 1Gi
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: CHAIN_ID
              value: "{{ .id }}"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: DRPC_ID
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_ENVIRONMENT
{{- end }}