pruning: false
chains:
  # Testnets
  - name: "curtis"
    id: "33111"
  # Mainnets
  - name: "ethereum"
    id: "1"
    extractor:
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 4Gi
    router:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
  - name: "optimism"
    id: "10"
  - name: "cronos"
    id: "25"
  - name: "rootstock"
    id: "30"
  - name: "telos"
    id: "40"
  - name: "bsc"
    id: "56"
    extractor:
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 4Gi
    router:
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
  - name: "gnosis"
    id: "100"
  - name: "thundercore"
    id: "108"
  - name: "fuse"
    id: "122"
  - name: "polygon"
    id: "137"
    extractor:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
    router:
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
  - name: "bttc"
    id: "199"
  - name: "fantom"
    id: "250"
  - name: "boba"
    id: "288"
  - name: "filecoin"
    id: "314"
  - name: "polygon-zkevm"
    id: "1101"
  - name: "core"
    id: "1116"
  - name: "moonbeam"
    id: "1284"
  - name: "moonriver"
    id: "1285"
  - name: "metis"
    id: "1088"
  - name: "kava"
    id: "2222"
  - name: "zetachain"
    id: "7000"
  - name: "base"
    id: "8453"
    extractor:
      resources:
        requests:
          cpu: 1000m
          memory: 4Gi
    router:
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
  - name: "haqq"
    id: "11235"
  - name: "arbitrum"
    id: "42161"
    router:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
  - name: "arbitrum-nova"
    id: "42170"
    extractor:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
  - name: "celo"
    id: "42220"
  - name: "avalanche"
    id: "43114"
  - name: "linea"
    id: "59144"
  - name: "boba-bnb"
    id: "56288"
  - name: "blast"
    id: "81457"
  - name: "scroll"
    id: "534352"
  - name: "harmony"
    id: "1666600000"
  - name: "skale-europa"
    id: "2046399126"
  - name: "mantle"
    id: "5000"
  - name: "zksync-era"
    id: "324"