name: Sushi - apps / evm

# force
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/apps-evm-e2e.yml"
      - "apps/evm/**"
      - "config/nextjs/**"
      - "config/react-query/**"
      - "config/router/**"
      - "config/tailwindcss/**"
      - "config/typescript/**"
      - "config/viem/**"
      - "config/wagmi/**"
      - "packages/**"

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./apps/evm

# https://playwright.dev/docs/ci#sharding
env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  NODE_OPTIONS: --max-old-space-size=8192
  NEXT_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain-id: [1,137,42161]
        node-version: [18]
        pnpm-version: [7.9.5]
        include:
          - chain-id: 1
            block-number: 17284226
            rpc-url: https://eth-mainnet.g.alchemy.com/v2
          - chain-id: 137
            block-number: 42259027
            rpc-url: https://polygon-mainnet.g.alchemy.com/v2
          - chain-id: 42161
            block-number: 91850294
            rpc-url: https://arb-mainnet.g.alchemy.com/v2
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: true

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Install playwright
        run: pnpm exec playwright install --with-deps chromium

      - name: Forge RPC cache
        uses: actions/cache@v3
        with:
            path: "$HOME/.foundry/cache"
            key: rpc-cache-${{ matrix.node-version }}-${{ matrix.chain-id }}-${{ matrix.block-number }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # /home/runner/work/sushiswap/sushiswap

      - name: Test EVM app
        run: pnpm test-evm-app
        env:
          ACADEMY_URL: 'https://academy.sushi.com'
          ANALYTICS_URL: 'https://analytics.sushi.com'
          BLOG_URL: 'https://blog.sushi.com'
          FURO_URL: 'https://furo.sushi.com'
          ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
          CHAIN_ID: ${{ matrix.chain-id }}
          DRPC_ID: ${{ secrets.DRPC_ID }}
          ANVIL_BLOCK_NUMBER: ${{ matrix.block-number }}
          ANVIL_FORK_URL: ${{ matrix.rpc-url }}
          ANVIL_PORT: 8545
          NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
          NEXT_PUBLIC_DRPC_ID: ${{ secrets.NEXT_PUBLIC_DRPC_ID }}
          NEXT_PUBLIC_TEST: true
        working-directory: .

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./apps/evm/test-results/