name: Sushi - apps / evm

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/apps-evm-e2e.yml"
      - "apps/evm/**"
      - "config/nextjs/**"
      - "config/router/**"
      - "config/tailwindcss/**"
      - "config/typescript/**"
      - "config/viem/**"
      - "config/wagmi/**"
      - "packages/**"
  workflow_dispatch:

env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=8192
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_FORCE: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 15
    strategy:
      matrix:
        block-number: [55359656]
        chain-id: [137]
        node-version: [20]
        pnpm-version: [8.15.3]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      # Has to be before setup node for caching to work
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Setup Node.js
        uses: buildjet/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        
      - name: Install Playwright Browsers
        run: npx playwright@1.37.0 install --with-deps chromium

      - name: Test
        run: pnpm exec turbo run test --filter evm
        env:
          ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
          ANVIL_BLOCK_NUMBER: ${{ matrix.block-number }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
          NEXT_PUBLIC_APP_ENV: 'test'
          NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
          NEXT_PUBLIC_CHAIN_ID: ${{ matrix.chain-id }}
          NEXT_PUBLIC_API_BASE_URL: 'https://mock-swap-api'
          NEXT_TELEMETRY_DISABLED: 1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./apps/evm/test-results/
          retention-days: 30