name: Sushi - apps / furo

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/apps-furo-e2e.yml"
      - "apps/furo/**"
      - "config/graph/**"
      - "config/nextjs/**"
      - "config/react-query/**"
      - "config/router/**"
      - "config/tailwindcss/**"
      - "config/typescript/**"
      - "config/viem/**"
      - "config/wagmi/**"
      - "packages/**"

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./apps/furo

# https://playwright.dev/docs/ci#sharding

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  NODE_OPTIONS: --max-old-space-size=8192
  NEXT_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e:
      timeout-minutes: 30
      runs-on: ubuntu-latest
      env:
        ANVIL_BLOCK_NUMBER: 42259027
      strategy:
        matrix:
          chain-id: [137]
          node-version: [18]
          pnpm-version: [8.8.0]
      steps:
        - name: Check out
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
            submodules: true

        - uses: pnpm/action-setup@v2
          with:
            version: ${{ matrix.pnpm-version }}

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

        - name: Cache pnpm
          uses: actions/cache@v3
          with:
            path: ~/.pnpm-store
            key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
            restore-keys: pnpm-

        - name: Install dependencies
          run: pnpm install
          working-directory: .

        - name: Install playwright
          run: pnpm exec playwright install --with-deps chromium

        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1

        - name: Test furo app
          run: pnpm test-furo-app
          env:
            ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
            PLAYWRIGHT_URL: http://localhost:3000/furo
            CHAIN_ID: ${{ matrix.chain-id }}
            ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
            ANVIL_PORT: 8545
            NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
            NEXT_PUBLIC_TEST: true
          working-directory: .

        - name: Upload test results
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: playwright-report
            path: ./apps/furo/test-results/