name: 'Chromatic'

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/chromatic.yml"
      - "config/tailwindcss/**"
      - "packages/ui/**"

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Build storybook
        run: pnpm exec turbo run build --filter=docs^...
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/docs
          buildScriptName: build
          exitOnceUploaded: true

